# Site settings
title: Kozhikoden Manyu
email: abhi@manyu.in
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://manyu.in" # the base hostname & protocol for your site
twitter_username: abhimanyuma
github_username:  abhimanyuma

# Build settings
markdown: kramdown

gems:
  - jekyll-gist
